spring:
  mvc:
    static-path-pattern: /**
    resources:
      static-locations: classpath:/templates/,classpath:/static/,classpath:/asset/
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    #发布用内置数据库，开发用server
    #url: jdbc:hsqldb:file:~/.hsqldb/db
    url: jdbc:hsqldb:hsql://localhost:9001/xdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.HSQLDialect
  jackson:
    default-property-inclusion: non_null
server:
  port: 8088
